### PR TITLE
Updated biohansel v.2.4.0 wrapper

### PR DESCRIPTION
**Pull request by glabbe**
I've also changed the publication title and list of authors

### CODE REVIEW

**Comment by glabbe** [comment]
@DarianHole can you please check that all our previous PR changes are included in this release, please modify as needed

**Comment by DarianHole** [comment]
@glabbe Changes looks good to me!

I do think that in the future we could add another test in the future for the wrapper but that isn't important for the moment.

**Comment by kbessonov1984** [comment]
@DarianHole  Is the [comment](https://github.com/phac-nml/galaxy_tools/pull/152#issuecomment-526702246) still valid for this commit or we can ignore it for the time being? Unit tests are always nice to have, but I agree that if there are no bugs, they are not essential for this commit.

**Comment by DarianHole** [comment]
No we can ignore it for the time being

**Comment by glabbe** [comment]
Thanks @DarianHole and @kbessonov1984 !  @Takadonet @apetkau , would it be possible to approve and merge the changes?  Please let me know if it looks OK.

**Pull request merged**
