### PR TITLE
Responding to Feedback

### PR DESCRIPTION
**Pull request by ConnorChato**
- [x]  The sparepeates need to be downloaded from source instead of manually inputted by user. 
- [x] The output needs to be adjusted to  show a more complete table. This table needs to be collapsable through galaxy's running of multiple separate inputs

### CODE REVIEW

**Review by apetkau — CHANGES_REQUESTED** [review]
Thanks so much @ConnorChato , this looks amazing. It's great to be able to remove that parameter requiring someone to pass in the repeats. Two comments I have:

1. Could you update the `galaxyN` version part from `galaxy0` to `galaxy1`, since you are modifying the behavior of the wrapper?
2. Do you know how the tool works when you don't pass the repeats file? I have a suspicion that it will automatically download this file each time. Could this cause conflicts when multiple instances of this tool are run at the same time? As an example, is it storing the repeats fasta file in a fixed location (where multiple running instances could overwrite each others files)? Or is this fasta file stored in a unique location for every run of the tool?

**Comment by ConnorChato** [comment]
> Thanks so much @ConnorChato , this looks amazing. It's great to be able to remove that parameter requiring someone to pass in the repeats. Two comments I have:
> 
> 1. Could you update the `galaxyN` version part from `galaxy0` to `galaxy1`, since you are modifying the behavior of the wrapper?
> 2. Do you know how the tool works when you don't pass the repeats file? I have a suspicion that it will automatically download this file each time. Could this cause conflicts when multiple instances of this tool are run at the same time? As an example, is it storing the repeats fasta file in a fixed location (where multiple running instances could overwrite each others files)? Or is this fasta file stored in a unique location for every run of the tool?

Updated Part 1. As for part 2 I think we should be okay for normal spatyper. When I've tested with CL version, if you explicitly pass blanks to -r and -o, it should check the status and past download times of current files to avoid this issue. 

```
Start the identification of repeats in Spa protein:
+ Check or download repeats fasta file in folder:  /home/connor/anaconda3/bin
        A previous download created sparepeats.fasta on: 2023-04-18 15:55:46
+ Check or download repeats types file in folder:  /home/connor/anaconda3/bin
        A previous download created spatypes.txt on: 2023-04-18 15:55:59
```

**Comment by ConnorChato** [comment]
Tried forcing the blanks into -r and -o and it caused errors, so it looks like defaults will have to do for now. Should behave the same way anyway.

**Review by apetkau — APPROVED** [review]
Okay. This all looks good for me. Thanks so much.

**Pull request merged**
