### PR TITLE
Adding Bowtie2 Maxins and Minins parameters

### PR DESCRIPTION
**Pull request by JenCabral**
Added maxins and minins to srst2 tool wrapper. Added a check in the perl file to ensure the maxin value is always higher than the minin value

### CODE REVIEW

**Comment by Takadonet** [comment]
A few planemo lint failed for srst2 and package_srst2.

https://travis-ci.org/phac-nml/galaxy_tools/builds/170796209#L768 . New requirement to have a sha256sum value associated when downloading something from the web. Best way to get it is download to your localhost then run sha256sum file.tar.gz 

https://travis-ci.org/phac-nml/galaxy_tools/builds/170796209#L822 Same requirement as above.

**Comment by Takadonet** [comment]
Also getting a <param > is missing a name error but looks like was added by accident @ https://github.com/JenCabral/galaxy_tools/blob/f1a0825f1a0268fd286eb385638057fb14fda2bb/tools/srst2/srst2.xml#L258

**Comment by JenCabral** [comment]
Fir the package_srst2 errors, I'll be submitting a new PR for some updates to that package so I will  update and include sha256sum values in that PR for the package

**Comment by Takadonet** [comment]
All good.

**Pull request merged**
