### PR TITLE
Update dependency version to match tool version

### PR DESCRIPTION
**Pull request by innovate-invent**

### CODE REVIEW

**Comment by innovate-invent** [comment]
@apetkau do you mind looking into the failed test?

**Comment by apetkau** [comment]
@innovate-invent no problem. It looks like some of the output files have changed slightly from what's in the test data. Specifically these files https://github.com/phac-nml/galaxy_tools/blob/ab874acc853c915a81db8dde5eae396002b9c873/tools/refseq_masher/test-data/SRR1203042_1-head4000-contains.tab and https://github.com/phac-nml/galaxy_tools/blob/ab874acc853c915a81db8dde5eae396002b9c873/tools/refseq_masher/test-data/SRR1203042_1-head4000-refseq_masher-matches-m2.tab

It's hard to view the diffs in the planemo output but it looks to be either that row orders in the files have changed or some floating point numbers are slightly different (e.g., `7.688639999999999e-108` vs `7.68864e-108`).

I'm wondering if you could run the tool on the example input files used by the tests (using e.g., [planemo serve](https://planemo.readthedocs.io/en/latest/commands.html#serve-command)) and just copy the output results files over the test data so that the tests pass with this version?

**Comment by innovate-invent** [comment]
I ran:
```
cd tools/refseq_masher/test-data
docker run --rm -v ${PWD}:/mnt quay.io/biocontainers/refseq_masher:0.1.2--py_0 refseq_masher -vv contains --output /mnt/SRR1203042_1-head4000-contains.tab --output-type tab --top-n-results 5 --parallelism "${GALAXY_SLOTS:-1}" --min-identity 0.9 --max-pvalue 0.01 "/mnt/SRR1203042_1-head4000.fastq"
2021-06-25 00:37:58,648 INFO: Grouped 1 fastqs into 1 groups [in /usr/local/lib/python3.9/site-packages/refseq_masher/utils.py:172]
2021-06-25 00:37:58,649 INFO: Collected 0 FASTA inputs and 1 read sets [in /usr/local/lib/python3.9/site-packages/refseq_masher/utils.py:185]
2021-06-25 00:37:58,649 INFO: Running Mash Screen with NCBI RefSeq sketch database against sample "SRR1203042-head4000" with inputs: ['/mnt/SRR1203042_1-head4000.fastq'] [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/screen.py:44]
Loading /usr/local/lib/python3.9/site-packages/refseq_masher/data/RefSeqSketches.msh...
   4669418 distinct hashes.
Streaming from /mnt/SRR1203042_1-head4000.fastq...
   Estimated distinct k-mers in mixture: 173443
Summing shared...
Computing coverage medians...
Writing output...
2021-06-25 00:38:18,423 INFO: Ran Mash Screen on all input. [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:143]
2021-06-25 00:38:18,423 INFO: Merging NCBI taxonomic information into results output. [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:146]
2021-06-25 00:38:18,425 INFO: Fetching all taxonomy info for 3 unique NCBI Taxonomy UIDs [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:35]
2021-06-25 00:38:18,426 INFO: Dropping columns with all NA values (ncol=32) [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:38]
2021-06-25 00:38:18,429 INFO: Columns with all NA values dropped (ncol=11) [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:40]
2021-06-25 00:38:18,429 INFO: Merging Mash results with relevant taxonomic information [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:41]
2021-06-25 00:38:18,432 INFO: Merged Mash results with taxonomy info [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:43]
2021-06-25 00:38:18,432 INFO: Merged taxonomic information into results output [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:148]
2021-06-25 00:38:18,432 INFO: Reordering output columns [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:149]
2021-06-25 00:38:18,434 INFO: Wrote output to "/mnt/SRR1203042_1-head4000-contains.tab" [in /usr/local/lib/python3.9/site-packages/refseq_masher/writers.py:20]

docker run --rm -v ${PWD}:/mnt quay.io/biocontainers/refseq_masher:0.1.2--py_0 refseq_masher -vv matches --output /mnt/SRR1203042_1-head4000-refseq_masher-matches-m2.tab --output-type tab --top-n-results 1 --min-kmer-threshold 2 -T "${TMPDIR:-/tmp}" "/mnt/SRR1203042_1-head4000.fastq"
2021-06-25 00:50:36,082 INFO: Grouped 1 fastqs into 1 groups [in /usr/local/lib/python3.9/site-packages/refseq_masher/utils.py:172]
2021-06-25 00:50:36,082 INFO: Collected 0 FASTA inputs and 1 read sets [in /usr/local/lib/python3.9/site-packages/refseq_masher/utils.py:185]
2021-06-25 00:50:36,085 INFO: Creating Mash sketch file at "/tmp/SRR1203042-head4000.msh" from "['/mnt/SRR1203042_1-head4000.fastq']" [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/sketch.py:76]
Estimated genome size: 2456.9
Estimated coverage:    2.03
Writing to /tmp/SRR1203042-head4000.msh...
2021-06-25 00:50:36,195 INFO: Created Mash sketch file at "/tmp/SRR1203042-head4000.msh" [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/sketch.py:82]
2021-06-25 00:50:36,196 INFO: Mash sketch database created for "['/mnt/SRR1203042_1-head4000.fastq']" at "/tmp/SRR1203042-head4000.msh" [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:109]
2021-06-25 00:50:36,196 INFO: Querying Mash sketches "/tmp/SRR1203042-head4000.msh" against RefSeq sketch database [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:110]
2021-06-25 00:50:36,685 INFO: Queried "/tmp/SRR1203042-head4000.msh" against RefSeq sketch database. Parsing into Pandas DataFrame [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:112]
2021-06-25 00:50:37,118 INFO: Parsed Mash distance results into DataFrame with 54924 entries [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:115]
2021-06-25 00:50:37,118 INFO: Deleting temporary sketch file "/tmp/SRR1203042-head4000.msh" [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:120]
2021-06-25 00:50:37,118 INFO: Sketch file "/tmp/SRR1203042-head4000.msh" deleted! [in /usr/local/lib/python3.9/site-packages/refseq_masher/mash/dist.py:122]
2021-06-25 00:50:37,119 INFO: Ran Mash dist on all input. Merging NCBI taxonomic information into results output. [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:94]
2021-06-25 00:50:37,127 INFO: Fetching all taxonomy info for 1 unique NCBI Taxonomy UIDs [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:35]
2021-06-25 00:50:37,128 INFO: Dropping columns with all NA values (ncol=32) [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:38]
2021-06-25 00:50:37,131 INFO: Columns with all NA values dropped (ncol=11) [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:40]
2021-06-25 00:50:37,131 INFO: Merging Mash results with relevant taxonomic information [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:41]
2021-06-25 00:50:37,134 INFO: Merged Mash results with taxonomy info [in /usr/local/lib/python3.9/site-packages/refseq_masher/taxonomy.py:43]
2021-06-25 00:50:37,134 INFO: Merged taxonomic info into results output [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:96]
2021-06-25 00:50:37,134 INFO: Reordering output columns [in /usr/local/lib/python3.9/site-packages/refseq_masher/cli.py:97]
2021-06-25 00:50:37,137 INFO: Wrote output to "/mnt/SRR1203042_1-head4000-refseq_masher-matches-m2.tab" [in /usr/local/lib/python3.9/site-packages/refseq_masher/writers.py:20]
```
with no change to the files.

**Comment by innovate-invent** [comment]
It looks like it is the way the CI hardware is doing floating point numbers. I don't anticipate a reasonable resolution to the test failing.
Can you merge this in so I can move forward with deploying IRIDA?

**Comment by apetkau** [comment]
Yes. I think there must be differences maybe between different Python versions or dependency libraries (looks like the Docker container is using Python 3.9).

I think to solve this we can just remove direct comparison to a file for the tests and instead use `assert_contents` in the Galaxy tool testing suite: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-tests-test-output-assert-contents. I think asserting that the output files have the appropriate number of lines and columns is enough (`has_n_lines` and `has_n_columns`).

**Comment by apetkau** [comment]
Awesome. Thanks. Could you also remove the two test files: `SRR1203042_1-head4000-refseq_masher-matches-m2.tab` and `SRR1203042_1-head4000-contains.tab` from the test data directory since they are no longer needed.

**Review by apetkau — APPROVED** [review]
This looks great. Thanks so much for making all of the changes.

**Comment by innovate-invent** [comment]
Can you update the tool in the pipeline?

**Comment by apetkau** [comment]
I probably won't get around to this until next week sometime.

**Pull request merged**
